name: CI Build for Docker Action
on:
  push:
    branches: main
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: action/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run docker action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@EricSoder'

      - name: Output the time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"

      
